using System.Text;
using Discord.Rest;
using Discord.WebSocket;
using ShiggyBot.Components.V2;
using ShiggyBot.Utils;

namespace ShiggyBot.Commands.Core
{
    /// <summary>
    /// Command to test Discord's Components V2 message format.
    /// </summary>
    internal sealed class V2TestCommand : ICommand
    {
        private readonly ComponentsV2Client _v2Client;

        /// <summary>
        /// Initializes a new instance of the <see cref="V2TestCommand"/> class.
        /// </summary>
        /// <param name="v2Client">The Components V2 client.</param>
        internal V2TestCommand(ComponentsV2Client v2Client)
        {
            ArgumentNullException.ThrowIfNull(v2Client);
            _v2Client = v2Client;
        }

        /// <summary>Gets the command name.</summary>
        public string Name => "v2";

        /// <summary>Gets the command description.</summary>
        public string Description => "Test Discord Components V2 message format";

        /// <summary>Gets the command category.</summary>
        public string Category => "Core";

        /// <summary>Gets the command aliases.</summary>
        public IReadOnlyList<string> Aliases => [];

        /// <summary>Executes the command.</summary>
        public async Task ExecuteAsync(SocketUserMessage message, string[] args, DiscordSocketClient client)
        {
            ArgumentNullException.ThrowIfNull(message);
            ArgumentNullException.ThrowIfNull(args);
            ArgumentNullException.ThrowIfNull(client);

            RestApplication application = await client.GetApplicationInfoAsync().ConfigureAwait(false);
            if (message.Author.Id != application.Owner.Id)
            {
                return;
            }

            bool showRaw = args.Length > 0 && args[0].Equals("raw", StringComparison.OrdinalIgnoreCase);

            Uri gitHubIcon = new("https://github.com/fluidicon.png");

            byte[] fileContent = Encoding.UTF8.GetBytes(
                "ShiggyBot — Components V2 Test File\n" +
                "====================================\n" +
                $"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC\n" +
                "\n" +
                "This file was uploaded as a Components V2 File component.\n" +
                "The File component references attachment:// filenames in the\n" +
                "payload JSON, and the actual file data is sent as a multipart\n" +
                "form-data upload alongside the payload_json.\n");

            V2MessageBuilder builder = new V2MessageBuilder()
                .AddAttachment("v2-test.txt", fileContent, "Sample text file generated by bv2 command")
                .AddComponent(new SectionBuilder()
                    .AddTextDisplay(new TextDisplayBuilder().WithContent("# ShiggyBot — Components V2\n\nThis message showcases Discord's **Components V2** layout system with live components including a file attachment."))
                    .WithLinkButtonAccessory("View on GitHub", new Uri("https://github.com/kmmiio99o/ShiggyBot")))
                .AddComponent(new SeparatorBuilder()
                    .WithSpacing(SeparatorSpacing.Large)
                    .WithDivider(true))
                .AddComponent(new ContainerBuilder()
                    .WithAccentColor(0x57F287)
                    .AddComponent(new TextDisplayBuilder().WithContent("## Media Gallery\n\nImages displayed in a carousel using the `MediaGallery` component."))
                    .AddComponent(new MediaGalleryBuilder()
                        .AddItem(gitHubIcon, "GitHub logo")
                        .AddItem(new Uri("https://cdn.discordapp.com/embed/avatars/0.png"), "Discord default avatar (blue)")
                        .AddItem(new Uri("https://cdn.discordapp.com/embed/avatars/1.png"), "Discord default avatar (gray)")
                        .AddItem(new Uri("https://cdn.discordapp.com/embed/avatars/2.png"), "Discord default avatar (green)")
                        .AddItem(new Uri("https://cdn.discordapp.com/embed/avatars/3.png"), "Discord default avatar (orange)")))
                .AddComponent(new SeparatorBuilder()
                    .WithSpacing(SeparatorSpacing.Small))
                .AddComponent(new ContainerBuilder()
                    .WithAccentColor(0xED4245)
                    .AddComponent(new TextDisplayBuilder().WithContent("## File & Thumbnail\n\nThis container shows a `File` component referencing an uploaded `.txt` file, and a `Section` with a thumbnail accessory."))
                    .AddComponent(new FileBuilder().WithAttachment("v2-test.txt"))
                    .AddComponent(new SeparatorBuilder()
                        .WithSpacing(SeparatorSpacing.Small)
                        .WithDivider(false))
                    .AddComponent(new SectionBuilder()
                        .AddTextDisplay(new TextDisplayBuilder().WithContent("**Thumbnail accessory** — A `Section` can display a small thumbnail image alongside its text using `WithThumbnailAccessory`."))
                        .WithThumbnailAccessory(new ThumbnailBuilder()
                            .WithMedia(gitHubIcon)
                            .WithDescription("GitHub")))
                    .AddComponent(new SeparatorBuilder()
                        .WithSpacing(SeparatorSpacing.Small)
                        .WithDivider(false))
                    .AddComponent(new TextDisplayBuilder().WithContent("### Component Reference\n\n- **TextDisplay** — Renders markdown text inline\n- **Section** — Text group with optional button or thumbnail\n- **Container** — Colored grouping container\n- **Separator** — Visual divider with configurable spacing\n- **MediaGallery** — 1–10 image carousel\n- **Thumbnail** — Small accessory image\n- **File** — References uploaded attachments")));

            if (showRaw)
            {
                byte[] raw = builder.Build();
                string json = Encoding.UTF8.GetString(raw);
                await message.Channel.SendMessageAsync(embed: EmbedHelper.BuildInfoEmbed("V2 Message JSON", $"```json\n{json}\n```")).ConfigureAwait(false);
                return;
            }

            bool success = await _v2Client.SendMessageAsync(message.Channel.Id, builder).ConfigureAwait(false);

            if (!success)
            {
                await message.Channel.SendMessageAsync(embed: EmbedHelper.BuildErrorEmbed("Failed to send V2 message. Check logs for details.")).ConfigureAwait(false);
            }
        }
    }
}
